name: Build Docker Image
on:
  push:
    branches:
      - main
jobs:
    build:
      name: push docker image to docker hub
      runs-on: ubuntu-latest
      steps:
        - name: login to docker hub
          id: docker-hub
          uses: docker/login-action@v3
          with:
            username: ${{secrets.DOCKERHUB_USERNAME}}
            password: ${{secrets.DOCKERHUB_PASSWORD}}
        - name: build and push docker image to registry
          id: buil-push-docker-image
          uses: docker/build-push-action@v5
          with:
            context: .
            push: true
            tags: black1512/demo1:latest

